# Generated by Django 3.2 on 2021-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abavblink', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
